package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

/**
 * BarMenuItemAudit generated by hbm2java
 */
public class BarMenuItemAudit implements java.io.Serializable {

	private BarMenuItemAuditId id;

	public BarMenuItemAudit() {
	}

	public BarMenuItemAudit(BarMenuItemAuditId id) {
		this.id = id;
	}

	public BarMenuItemAuditId getId() {
		return this.id;
	}

	public void setId(BarMenuItemAuditId id) {
		this.id = id;
	}

}
