package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

/**
 * BarMenuAudit generated by hbm2java
 */
public class BarMenuAudit implements java.io.Serializable {

	private BarMenuAuditId id;

	public BarMenuAudit() {
	}

	public BarMenuAudit(BarMenuAuditId id) {
		this.id = id;
	}

	public BarMenuAuditId getId() {
		return this.id;
	}

	public void setId(BarMenuAuditId id) {
		this.id = id;
	}

}
