package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

import java.util.Date;

/**
 * BookingHistoryId generated by hbm2java
 */
public class BookingHistoryId implements java.io.Serializable {

	private Long id;
	private Long customerId;
	private Long diningTableId;
	private Long actualDiningTableId;
	private Date bookingDate;
	private Date bookingTime;
	private Short bookingDuration;
	private Float spendLimit;
	private Date updatedAt;
	private Long updatedBy;

	public BookingHistoryId() {
	}

	public BookingHistoryId(Long id, Long customerId, Long diningTableId, Long actualDiningTableId, Date bookingDate,
			Date bookingTime, Short bookingDuration, Float spendLimit, Date updatedAt, Long updatedBy) {
		this.id = id;
		this.customerId = customerId;
		this.diningTableId = diningTableId;
		this.actualDiningTableId = actualDiningTableId;
		this.bookingDate = bookingDate;
		this.bookingTime = bookingTime;
		this.bookingDuration = bookingDuration;
		this.spendLimit = spendLimit;
		this.updatedAt = updatedAt;
		this.updatedBy = updatedBy;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Long customerId) {
		this.customerId = customerId;
	}

	public Long getDiningTableId() {
		return this.diningTableId;
	}

	public void setDiningTableId(Long diningTableId) {
		this.diningTableId = diningTableId;
	}

	public Long getActualDiningTableId() {
		return this.actualDiningTableId;
	}

	public void setActualDiningTableId(Long actualDiningTableId) {
		this.actualDiningTableId = actualDiningTableId;
	}

	public Date getBookingDate() {
		return this.bookingDate;
	}

	public void setBookingDate(Date bookingDate) {
		this.bookingDate = bookingDate;
	}

	public Date getBookingTime() {
		return this.bookingTime;
	}

	public void setBookingTime(Date bookingTime) {
		this.bookingTime = bookingTime;
	}

	public Short getBookingDuration() {
		return this.bookingDuration;
	}

	public void setBookingDuration(Short bookingDuration) {
		this.bookingDuration = bookingDuration;
	}

	public Float getSpendLimit() {
		return this.spendLimit;
	}

	public void setSpendLimit(Float spendLimit) {
		this.spendLimit = spendLimit;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Long updatedBy) {
		this.updatedBy = updatedBy;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BookingHistoryId))
			return false;
		BookingHistoryId castOther = (BookingHistoryId) other;

		return ((this.getId() == castOther.getId())
				|| (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())))
				&& ((this.getCustomerId() == castOther.getCustomerId()) || (this.getCustomerId() != null
						&& castOther.getCustomerId() != null && this.getCustomerId().equals(castOther.getCustomerId())))
				&& ((this.getDiningTableId() == castOther.getDiningTableId())
						|| (this.getDiningTableId() != null && castOther.getDiningTableId() != null
								&& this.getDiningTableId().equals(castOther.getDiningTableId())))
				&& ((this.getActualDiningTableId() == castOther.getActualDiningTableId())
						|| (this.getActualDiningTableId() != null && castOther.getActualDiningTableId() != null
								&& this.getActualDiningTableId().equals(castOther.getActualDiningTableId())))
				&& ((this.getBookingDate() == castOther.getBookingDate())
						|| (this.getBookingDate() != null && castOther.getBookingDate() != null
								&& this.getBookingDate().equals(castOther.getBookingDate())))
				&& ((this.getBookingTime() == castOther.getBookingTime())
						|| (this.getBookingTime() != null && castOther.getBookingTime() != null
								&& this.getBookingTime().equals(castOther.getBookingTime())))
				&& ((this.getBookingDuration() == castOther.getBookingDuration())
						|| (this.getBookingDuration() != null && castOther.getBookingDuration() != null
								&& this.getBookingDuration().equals(castOther.getBookingDuration())))
				&& ((this.getSpendLimit() == castOther.getSpendLimit()) || (this.getSpendLimit() != null
						&& castOther.getSpendLimit() != null && this.getSpendLimit().equals(castOther.getSpendLimit())))
				&& ((this.getUpdatedAt() == castOther.getUpdatedAt()) || (this.getUpdatedAt() != null
						&& castOther.getUpdatedAt() != null && this.getUpdatedAt().equals(castOther.getUpdatedAt())))
				&& ((this.getUpdatedBy() == castOther.getUpdatedBy()) || (this.getUpdatedBy() != null
						&& castOther.getUpdatedBy() != null && this.getUpdatedBy().equals(castOther.getUpdatedBy())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getCustomerId() == null ? 0 : this.getCustomerId().hashCode());
		result = 37 * result + (getDiningTableId() == null ? 0 : this.getDiningTableId().hashCode());
		result = 37 * result + (getActualDiningTableId() == null ? 0 : this.getActualDiningTableId().hashCode());
		result = 37 * result + (getBookingDate() == null ? 0 : this.getBookingDate().hashCode());
		result = 37 * result + (getBookingTime() == null ? 0 : this.getBookingTime().hashCode());
		result = 37 * result + (getBookingDuration() == null ? 0 : this.getBookingDuration().hashCode());
		result = 37 * result + (getSpendLimit() == null ? 0 : this.getSpendLimit().hashCode());
		result = 37 * result + (getUpdatedAt() == null ? 0 : this.getUpdatedAt().hashCode());
		result = 37 * result + (getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode());
		return result;
	}

}
