package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

/**
 * BookingAudit generated by hbm2java
 */
public class BookingAudit implements java.io.Serializable {

	private BookingAuditId id;

	public BookingAudit() {
	}

	public BookingAudit(BookingAuditId id) {
		this.id = id;
	}

	public BookingAuditId getId() {
		return this.id;
	}

	public void setId(BookingAuditId id) {
		this.id = id;
	}

}
