package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Booking generated by hbm2java
 */
public class Booking implements java.io.Serializable {

	private long id;
	private Customer customer;
	private Long diningTableId;
	private Long actualDiningTableId;
	private Date bookingDate;
	private Date bookingTime;
	private Short bookingDuration;
	private Float spendLimit;
	private Date updatedAt;
	private Long updatedBy;
	private Set sessions = new HashSet(0);

	public Booking() {
	}

	public Booking(long id) {
		this.id = id;
	}

	public Booking(long id, Customer customer, Long diningTableId, Long actualDiningTableId, Date bookingDate,
			Date bookingTime, Short bookingDuration, Float spendLimit, Date updatedAt, Long updatedBy, Set sessions) {
		this.id = id;
		this.customer = customer;
		this.diningTableId = diningTableId;
		this.actualDiningTableId = actualDiningTableId;
		this.bookingDate = bookingDate;
		this.bookingTime = bookingTime;
		this.bookingDuration = bookingDuration;
		this.spendLimit = spendLimit;
		this.updatedAt = updatedAt;
		this.updatedBy = updatedBy;
		this.sessions = sessions;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Long getDiningTableId() {
		return this.diningTableId;
	}

	public void setDiningTableId(Long diningTableId) {
		this.diningTableId = diningTableId;
	}

	public Long getActualDiningTableId() {
		return this.actualDiningTableId;
	}

	public void setActualDiningTableId(Long actualDiningTableId) {
		this.actualDiningTableId = actualDiningTableId;
	}

	public Date getBookingDate() {
		return this.bookingDate;
	}

	public void setBookingDate(Date bookingDate) {
		this.bookingDate = bookingDate;
	}

	public Date getBookingTime() {
		return this.bookingTime;
	}

	public void setBookingTime(Date bookingTime) {
		this.bookingTime = bookingTime;
	}

	public Short getBookingDuration() {
		return this.bookingDuration;
	}

	public void setBookingDuration(Short bookingDuration) {
		this.bookingDuration = bookingDuration;
	}

	public Float getSpendLimit() {
		return this.spendLimit;
	}

	public void setSpendLimit(Float spendLimit) {
		this.spendLimit = spendLimit;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Long updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Set getSessions() {
		return this.sessions;
	}

	public void setSessions(Set sessions) {
		this.sessions = sessions;
	}

}
