package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

/**
 * BotAudit generated by hbm2java
 */
public class BotAudit implements java.io.Serializable {

	private BotAuditId id;

	public BotAudit() {
	}

	public BotAudit(BotAuditId id) {
		this.id = id;
	}

	public BotAuditId getId() {
		return this.id;
	}

	public void setId(BotAuditId id) {
		this.id = id;
	}

}
