package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

/**
 * BusinessOwnerEntityAudit generated by hbm2java
 */
public class BusinessOwnerEntityAudit implements java.io.Serializable {

	private BusinessOwnerEntityAuditId id;

	public BusinessOwnerEntityAudit() {
	}

	public BusinessOwnerEntityAudit(BusinessOwnerEntityAuditId id) {
		this.id = id;
	}

	public BusinessOwnerEntityAuditId getId() {
		return this.id;
	}

	public void setId(BusinessOwnerEntityAuditId id) {
		this.id = id;
	}

}
