package com.ignis.model;
// Generated 4 Aug, 2019 8:15:16 PM by Hibernate Tools 5.4.3.Final

/**
 * BusinessOwnerAudit generated by hbm2java
 */
public class BusinessOwnerAudit implements java.io.Serializable {

	private BusinessOwnerAuditId id;

	public BusinessOwnerAudit() {
	}

	public BusinessOwnerAudit(BusinessOwnerAuditId id) {
		this.id = id;
	}

	public BusinessOwnerAuditId getId() {
		return this.id;
	}

	public void setId(BusinessOwnerAuditId id) {
		this.id = id;
	}

}
