package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Country generated by hbm2java
 */
public class Country implements java.io.Serializable {

	private String iso;
	private String name;
	private String iso3;
	private int phoneCode;
	private Integer numCode;
	private Set taxes = new HashSet(0);

	public Country() {
	}

	public Country(String iso, String name, int phoneCode) {
		this.iso = iso;
		this.name = name;
		this.phoneCode = phoneCode;
	}

	public Country(String iso, String name, String iso3, int phoneCode, Integer numCode, Set taxes) {
		this.iso = iso;
		this.name = name;
		this.iso3 = iso3;
		this.phoneCode = phoneCode;
		this.numCode = numCode;
		this.taxes = taxes;
	}

	public String getIso() {
		return this.iso;
	}

	public void setIso(String iso) {
		this.iso = iso;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getIso3() {
		return this.iso3;
	}

	public void setIso3(String iso3) {
		this.iso3 = iso3;
	}

	public int getPhoneCode() {
		return this.phoneCode;
	}

	public void setPhoneCode(int phoneCode) {
		this.phoneCode = phoneCode;
	}

	public Integer getNumCode() {
		return this.numCode;
	}

	public void setNumCode(Integer numCode) {
		this.numCode = numCode;
	}

	public Set getTaxes() {
		return this.taxes;
	}

	public void setTaxes(Set taxes) {
		this.taxes = taxes;
	}

}
