package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

/**
 * CountryNewId generated by hbm2java
 */
public class CountryNewId implements java.io.Serializable {

	private Integer id;
	private String iso;
	private String name;
	private String nicename;
	private String iso3;
	private Integer numCode;
	private int phoneCode;

	public CountryNewId() {
	}

	public CountryNewId(String iso, String name, String nicename, int phoneCode) {
		this.iso = iso;
		this.name = name;
		this.nicename = nicename;
		this.phoneCode = phoneCode;
	}

	public CountryNewId(Integer id, String iso, String name, String nicename, String iso3, Integer numCode,
			int phoneCode) {
		this.id = id;
		this.iso = iso;
		this.name = name;
		this.nicename = nicename;
		this.iso3 = iso3;
		this.numCode = numCode;
		this.phoneCode = phoneCode;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getIso() {
		return this.iso;
	}

	public void setIso(String iso) {
		this.iso = iso;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNicename() {
		return this.nicename;
	}

	public void setNicename(String nicename) {
		this.nicename = nicename;
	}

	public String getIso3() {
		return this.iso3;
	}

	public void setIso3(String iso3) {
		this.iso3 = iso3;
	}

	public Integer getNumCode() {
		return this.numCode;
	}

	public void setNumCode(Integer numCode) {
		this.numCode = numCode;
	}

	public int getPhoneCode() {
		return this.phoneCode;
	}

	public void setPhoneCode(int phoneCode) {
		this.phoneCode = phoneCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CountryNewId))
			return false;
		CountryNewId castOther = (CountryNewId) other;

		return ((this.getId() == castOther.getId())
				|| (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())))
				&& ((this.getIso() == castOther.getIso()) || (this.getIso() != null && castOther.getIso() != null
						&& this.getIso().equals(castOther.getIso())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())))
				&& ((this.getNicename() == castOther.getNicename()) || (this.getNicename() != null
						&& castOther.getNicename() != null && this.getNicename().equals(castOther.getNicename())))
				&& ((this.getIso3() == castOther.getIso3()) || (this.getIso3() != null && castOther.getIso3() != null
						&& this.getIso3().equals(castOther.getIso3())))
				&& ((this.getNumCode() == castOther.getNumCode()) || (this.getNumCode() != null
						&& castOther.getNumCode() != null && this.getNumCode().equals(castOther.getNumCode())))
				&& (this.getPhoneCode() == castOther.getPhoneCode());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getIso() == null ? 0 : this.getIso().hashCode());
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getNicename() == null ? 0 : this.getNicename().hashCode());
		result = 37 * result + (getIso3() == null ? 0 : this.getIso3().hashCode());
		result = 37 * result + (getNumCode() == null ? 0 : this.getNumCode().hashCode());
		result = 37 * result + this.getPhoneCode();
		return result;
	}

}
