package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

/**
 * CountryNew generated by hbm2java
 */
public class CountryNew implements java.io.Serializable {

	private CountryNewId id;

	public CountryNew() {
	}

	public CountryNew(CountryNewId id) {
		this.id = id;
	}

	public CountryNewId getId() {
		return this.id;
	}

	public void setId(CountryNewId id) {
		this.id = id;
	}

}
