package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Currency generated by hbm2java
 */
public class Currency implements java.io.Serializable {

	private String code;
	private String name;
	private String symbol;
	private Set barMenuItems = new HashSet(0);
	private Set kitchenMenuItems = new HashSet(0);

	public Currency() {
	}

	public Currency(String code, String name, String symbol) {
		this.code = code;
		this.name = name;
		this.symbol = symbol;
	}

	public Currency(String code, String name, String symbol, Set barMenuItems, Set kitchenMenuItems) {
		this.code = code;
		this.name = name;
		this.symbol = symbol;
		this.barMenuItems = barMenuItems;
		this.kitchenMenuItems = kitchenMenuItems;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSymbol() {
		return this.symbol;
	}

	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}

	public Set getBarMenuItems() {
		return this.barMenuItems;
	}

	public void setBarMenuItems(Set barMenuItems) {
		this.barMenuItems = barMenuItems;
	}

	public Set getKitchenMenuItems() {
		return this.kitchenMenuItems;
	}

	public void setKitchenMenuItems(Set kitchenMenuItems) {
		this.kitchenMenuItems = kitchenMenuItems;
	}

}
