package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

/**
 * CustomerAudit generated by hbm2java
 */
public class CustomerAudit implements java.io.Serializable {

	private CustomerAuditId id;

	public CustomerAudit() {
	}

	public CustomerAudit(CustomerAuditId id) {
		this.id = id;
	}

	public CustomerAuditId getId() {
		return this.id;
	}

	public void setId(CustomerAuditId id) {
		this.id = id;
	}

}
