package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

	private long id;
	private String username;
	private Integer mobileNo;
	private String email;
	private String passhash;
	private String firstName;
	private String lastName;
	private String address;
	private Serializable foodieType;
	private Date updatedAt;
	private Long updatedBy;
	private Set memorieses = new HashSet(0);
	private Set reviews = new HashSet(0);
	private Set sessionCustomers = new HashSet(0);
	private Set bookings = new HashSet(0);

	public Customer() {
	}

	public Customer(long id) {
		this.id = id;
	}

	public Customer(long id, String username, Integer mobileNo, String email, String passhash, String firstName,
			String lastName, String address, Serializable foodieType, Date updatedAt, Long updatedBy, Set memorieses,
			Set reviews, Set sessionCustomers, Set bookings) {
		this.id = id;
		this.username = username;
		this.mobileNo = mobileNo;
		this.email = email;
		this.passhash = passhash;
		this.firstName = firstName;
		this.lastName = lastName;
		this.address = address;
		this.foodieType = foodieType;
		this.updatedAt = updatedAt;
		this.updatedBy = updatedBy;
		this.memorieses = memorieses;
		this.reviews = reviews;
		this.sessionCustomers = sessionCustomers;
		this.bookings = bookings;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Integer getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(Integer mobileNo) {
		this.mobileNo = mobileNo;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPasshash() {
		return this.passhash;
	}

	public void setPasshash(String passhash) {
		this.passhash = passhash;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Serializable getFoodieType() {
		return this.foodieType;
	}

	public void setFoodieType(Serializable foodieType) {
		this.foodieType = foodieType;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Long updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Set getMemorieses() {
		return this.memorieses;
	}

	public void setMemorieses(Set memorieses) {
		this.memorieses = memorieses;
	}

	public Set getReviews() {
		return this.reviews;
	}

	public void setReviews(Set reviews) {
		this.reviews = reviews;
	}

	public Set getSessionCustomers() {
		return this.sessionCustomers;
	}

	public void setSessionCustomers(Set sessionCustomers) {
		this.sessionCustomers = sessionCustomers;
	}

	public Set getBookings() {
		return this.bookings;
	}

	public void setBookings(Set bookings) {
		this.bookings = bookings;
	}

}
