package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DiningTable generated by hbm2java
 */
public class DiningTable implements java.io.Serializable {

	private long id;
	private Layout layout;
	private String type;
	private Integer x;
	private Integer y;
	private Integer width;
	private Integer height;
	private Integer radius;
	private Float SAngle;
	private Float EAngle;
	private Date updatedAt;
	private Long updatedBy;
	private Set sessions = new HashSet(0);

	public DiningTable() {
	}

	public DiningTable(long id) {
		this.id = id;
	}

	public DiningTable(long id, Layout layout, String type, Integer x, Integer y, Integer width, Integer height,
			Integer radius, Float SAngle, Float EAngle, Date updatedAt, Long updatedBy, Set sessions) {
		this.id = id;
		this.layout = layout;
		this.type = type;
		this.x = x;
		this.y = y;
		this.width = width;
		this.height = height;
		this.radius = radius;
		this.SAngle = SAngle;
		this.EAngle = EAngle;
		this.updatedAt = updatedAt;
		this.updatedBy = updatedBy;
		this.sessions = sessions;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Layout getLayout() {
		return this.layout;
	}

	public void setLayout(Layout layout) {
		this.layout = layout;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Integer getX() {
		return this.x;
	}

	public void setX(Integer x) {
		this.x = x;
	}

	public Integer getY() {
		return this.y;
	}

	public void setY(Integer y) {
		this.y = y;
	}

	public Integer getWidth() {
		return this.width;
	}

	public void setWidth(Integer width) {
		this.width = width;
	}

	public Integer getHeight() {
		return this.height;
	}

	public void setHeight(Integer height) {
		this.height = height;
	}

	public Integer getRadius() {
		return this.radius;
	}

	public void setRadius(Integer radius) {
		this.radius = radius;
	}

	public Float getSAngle() {
		return this.SAngle;
	}

	public void setSAngle(Float SAngle) {
		this.SAngle = SAngle;
	}

	public Float getEAngle() {
		return this.EAngle;
	}

	public void setEAngle(Float EAngle) {
		this.EAngle = EAngle;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Long updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Set getSessions() {
		return this.sessions;
	}

	public void setSessions(Set sessions) {
		this.sessions = sessions;
	}

}
