package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

/**
 * DiningTableAudit generated by hbm2java
 */
public class DiningTableAudit implements java.io.Serializable {

	private DiningTableAuditId id;

	public DiningTableAudit() {
	}

	public DiningTableAudit(DiningTableAuditId id) {
		this.id = id;
	}

	public DiningTableAuditId getId() {
		return this.id;
	}

	public void setId(DiningTableAuditId id) {
		this.id = id;
	}

}
