package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

import java.util.Date;

/**
 * DiningTableAuditId generated by hbm2java
 */
public class DiningTableAuditId implements java.io.Serializable {

	private Character action;
	private long id;
	private String type;
	private Integer x;
	private Integer y;
	private Integer width;
	private Integer height;
	private Integer radius;
	private Float SAngle;
	private Float EAngle;
	private Integer layoutId;
	private Date updatedAt;
	private Long updatedBy;

	public DiningTableAuditId() {
	}

	public DiningTableAuditId(long id) {
		this.id = id;
	}

	public DiningTableAuditId(Character action, long id, String type, Integer x, Integer y, Integer width,
			Integer height, Integer radius, Float SAngle, Float EAngle, Integer layoutId, Date updatedAt,
			Long updatedBy) {
		this.action = action;
		this.id = id;
		this.type = type;
		this.x = x;
		this.y = y;
		this.width = width;
		this.height = height;
		this.radius = radius;
		this.SAngle = SAngle;
		this.EAngle = EAngle;
		this.layoutId = layoutId;
		this.updatedAt = updatedAt;
		this.updatedBy = updatedBy;
	}

	public Character getAction() {
		return this.action;
	}

	public void setAction(Character action) {
		this.action = action;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Integer getX() {
		return this.x;
	}

	public void setX(Integer x) {
		this.x = x;
	}

	public Integer getY() {
		return this.y;
	}

	public void setY(Integer y) {
		this.y = y;
	}

	public Integer getWidth() {
		return this.width;
	}

	public void setWidth(Integer width) {
		this.width = width;
	}

	public Integer getHeight() {
		return this.height;
	}

	public void setHeight(Integer height) {
		this.height = height;
	}

	public Integer getRadius() {
		return this.radius;
	}

	public void setRadius(Integer radius) {
		this.radius = radius;
	}

	public Float getSAngle() {
		return this.SAngle;
	}

	public void setSAngle(Float SAngle) {
		this.SAngle = SAngle;
	}

	public Float getEAngle() {
		return this.EAngle;
	}

	public void setEAngle(Float EAngle) {
		this.EAngle = EAngle;
	}

	public Integer getLayoutId() {
		return this.layoutId;
	}

	public void setLayoutId(Integer layoutId) {
		this.layoutId = layoutId;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Long updatedBy) {
		this.updatedBy = updatedBy;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DiningTableAuditId))
			return false;
		DiningTableAuditId castOther = (DiningTableAuditId) other;

		return ((this.getAction() == castOther.getAction()) || (this.getAction() != null
				&& castOther.getAction() != null && this.getAction().equals(castOther.getAction())))
				&& (this.getId() == castOther.getId())
				&& ((this.getType() == castOther.getType()) || (this.getType() != null && castOther.getType() != null
						&& this.getType().equals(castOther.getType())))
				&& ((this.getX() == castOther.getX())
						|| (this.getX() != null && castOther.getX() != null && this.getX().equals(castOther.getX())))
				&& ((this.getY() == castOther.getY())
						|| (this.getY() != null && castOther.getY() != null && this.getY().equals(castOther.getY())))
				&& ((this.getWidth() == castOther.getWidth()) || (this.getWidth() != null
						&& castOther.getWidth() != null && this.getWidth().equals(castOther.getWidth())))
				&& ((this.getHeight() == castOther.getHeight()) || (this.getHeight() != null
						&& castOther.getHeight() != null && this.getHeight().equals(castOther.getHeight())))
				&& ((this.getRadius() == castOther.getRadius()) || (this.getRadius() != null
						&& castOther.getRadius() != null && this.getRadius().equals(castOther.getRadius())))
				&& ((this.getSAngle() == castOther.getSAngle()) || (this.getSAngle() != null
						&& castOther.getSAngle() != null && this.getSAngle().equals(castOther.getSAngle())))
				&& ((this.getEAngle() == castOther.getEAngle()) || (this.getEAngle() != null
						&& castOther.getEAngle() != null && this.getEAngle().equals(castOther.getEAngle())))
				&& ((this.getLayoutId() == castOther.getLayoutId()) || (this.getLayoutId() != null
						&& castOther.getLayoutId() != null && this.getLayoutId().equals(castOther.getLayoutId())))
				&& ((this.getUpdatedAt() == castOther.getUpdatedAt()) || (this.getUpdatedAt() != null
						&& castOther.getUpdatedAt() != null && this.getUpdatedAt().equals(castOther.getUpdatedAt())))
				&& ((this.getUpdatedBy() == castOther.getUpdatedBy()) || (this.getUpdatedBy() != null
						&& castOther.getUpdatedBy() != null && this.getUpdatedBy().equals(castOther.getUpdatedBy())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAction() == null ? 0 : this.getAction().hashCode());
		result = 37 * result + (int) this.getId();
		result = 37 * result + (getType() == null ? 0 : this.getType().hashCode());
		result = 37 * result + (getX() == null ? 0 : this.getX().hashCode());
		result = 37 * result + (getY() == null ? 0 : this.getY().hashCode());
		result = 37 * result + (getWidth() == null ? 0 : this.getWidth().hashCode());
		result = 37 * result + (getHeight() == null ? 0 : this.getHeight().hashCode());
		result = 37 * result + (getRadius() == null ? 0 : this.getRadius().hashCode());
		result = 37 * result + (getSAngle() == null ? 0 : this.getSAngle().hashCode());
		result = 37 * result + (getEAngle() == null ? 0 : this.getEAngle().hashCode());
		result = 37 * result + (getLayoutId() == null ? 0 : this.getLayoutId().hashCode());
		result = 37 * result + (getUpdatedAt() == null ? 0 : this.getUpdatedAt().hashCode());
		result = 37 * result + (getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode());
		return result;
	}

}
