package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

/**
 * DiscountAudit generated by hbm2java
 */
public class DiscountAudit implements java.io.Serializable {

	private DiscountAuditId id;

	public DiscountAudit() {
	}

	public DiscountAudit(DiscountAuditId id) {
		this.id = id;
	}

	public DiscountAuditId getId() {
		return this.id;
	}

	public void setId(DiscountAuditId id) {
		this.id = id;
	}

}
