package com.ignis.model;
// Generated 4 Aug, 2019 8:15:16 PM by Hibernate Tools 5.4.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Entity generated by hbm2java
 */
public class Entity implements java.io.Serializable {

	private long id;
	private String name;
	private String regNo;
	private Date updatedAt;
	private Long updatedBy;
	private Set businessOwnerEntities = new HashSet(0);
	private Set establishments = new HashSet(0);

	public Entity() {
	}

	public Entity(long id) {
		this.id = id;
	}

	public Entity(long id, String name, String regNo, Date updatedAt, Long updatedBy, Set businessOwnerEntities,
			Set establishments) {
		this.id = id;
		this.name = name;
		this.regNo = regNo;
		this.updatedAt = updatedAt;
		this.updatedBy = updatedBy;
		this.businessOwnerEntities = businessOwnerEntities;
		this.establishments = establishments;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getRegNo() {
		return this.regNo;
	}

	public void setRegNo(String regNo) {
		this.regNo = regNo;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Long updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Set getBusinessOwnerEntities() {
		return this.businessOwnerEntities;
	}

	public void setBusinessOwnerEntities(Set businessOwnerEntities) {
		this.businessOwnerEntities = businessOwnerEntities;
	}

	public Set getEstablishments() {
		return this.establishments;
	}

	public void setEstablishments(Set establishments) {
		this.establishments = establishments;
	}

}
