package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

/**
 * EstablishmentLayoutAudit generated by hbm2java
 */
public class EstablishmentLayoutAudit implements java.io.Serializable {

	private EstablishmentLayoutAuditId id;

	public EstablishmentLayoutAudit() {
	}

	public EstablishmentLayoutAudit(EstablishmentLayoutAuditId id) {
		this.id = id;
	}

	public EstablishmentLayoutAuditId getId() {
		return this.id;
	}

	public void setId(EstablishmentLayoutAuditId id) {
		this.id = id;
	}

}
