package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

/**
 * EstablishmentAudit generated by hbm2java
 */
public class EstablishmentAudit implements java.io.Serializable {

	private EstablishmentAuditId id;

	public EstablishmentAudit() {
	}

	public EstablishmentAudit(EstablishmentAuditId id) {
		this.id = id;
	}

	public EstablishmentAuditId getId() {
		return this.id;
	}

	public void setId(EstablishmentAuditId id) {
		this.id = id;
	}

}
