package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

import java.util.Date;

/**
 * EstablishmentLayoutId generated by hbm2java
 */
public class EstablishmentLayoutId implements java.io.Serializable {

	private Long layoutId;
	private Long establishmentId;
	private Date updatedAt;
	private Long updatedBy;

	public EstablishmentLayoutId() {
	}

	public EstablishmentLayoutId(Long layoutId, Long establishmentId, Date updatedAt, Long updatedBy) {
		this.layoutId = layoutId;
		this.establishmentId = establishmentId;
		this.updatedAt = updatedAt;
		this.updatedBy = updatedBy;
	}

	public Long getLayoutId() {
		return this.layoutId;
	}

	public void setLayoutId(Long layoutId) {
		this.layoutId = layoutId;
	}

	public Long getEstablishmentId() {
		return this.establishmentId;
	}

	public void setEstablishmentId(Long establishmentId) {
		this.establishmentId = establishmentId;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Long updatedBy) {
		this.updatedBy = updatedBy;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EstablishmentLayoutId))
			return false;
		EstablishmentLayoutId castOther = (EstablishmentLayoutId) other;

		return ((this.getLayoutId() == castOther.getLayoutId()) || (this.getLayoutId() != null
				&& castOther.getLayoutId() != null && this.getLayoutId().equals(castOther.getLayoutId())))
				&& ((this.getEstablishmentId() == castOther.getEstablishmentId())
						|| (this.getEstablishmentId() != null && castOther.getEstablishmentId() != null
								&& this.getEstablishmentId().equals(castOther.getEstablishmentId())))
				&& ((this.getUpdatedAt() == castOther.getUpdatedAt()) || (this.getUpdatedAt() != null
						&& castOther.getUpdatedAt() != null && this.getUpdatedAt().equals(castOther.getUpdatedAt())))
				&& ((this.getUpdatedBy() == castOther.getUpdatedBy()) || (this.getUpdatedBy() != null
						&& castOther.getUpdatedBy() != null && this.getUpdatedBy().equals(castOther.getUpdatedBy())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getLayoutId() == null ? 0 : this.getLayoutId().hashCode());
		result = 37 * result + (getEstablishmentId() == null ? 0 : this.getEstablishmentId().hashCode());
		result = 37 * result + (getUpdatedAt() == null ? 0 : this.getUpdatedAt().hashCode());
		result = 37 * result + (getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode());
		return result;
	}

}
