package com.ignis.model;
// Generated 4 Aug, 2019 8:15:16 PM by Hibernate Tools 5.4.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Establishment generated by hbm2java
 */
public class Establishment implements java.io.Serializable {

	private long id;
	private Entity entity;
	private Layout layout;
	private Integer establishmentNo;
	private String address;
	private Date updatedAt;
	private Long updatedBy;
	private Set staffs = new HashSet(0);

	public Establishment() {
	}

	public Establishment(long id) {
		this.id = id;
	}

	public Establishment(long id, Entity entity, Layout layout, Integer establishmentNo, String address, Date updatedAt,
			Long updatedBy, Set staffs) {
		this.id = id;
		this.entity = entity;
		this.layout = layout;
		this.establishmentNo = establishmentNo;
		this.address = address;
		this.updatedAt = updatedAt;
		this.updatedBy = updatedBy;
		this.staffs = staffs;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Entity getEntity() {
		return this.entity;
	}

	public void setEntity(Entity entity) {
		this.entity = entity;
	}

	public Layout getLayout() {
		return this.layout;
	}

	public void setLayout(Layout layout) {
		this.layout = layout;
	}

	public Integer getEstablishmentNo() {
		return this.establishmentNo;
	}

	public void setEstablishmentNo(Integer establishmentNo) {
		this.establishmentNo = establishmentNo;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Long updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Set getStaffs() {
		return this.staffs;
	}

	public void setStaffs(Set staffs) {
		this.staffs = staffs;
	}

}
