package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

/**
 * GeographyColumns generated by hbm2java
 */
public class GeographyColumns implements java.io.Serializable {

	private GeographyColumnsId id;

	public GeographyColumns() {
	}

	public GeographyColumns(GeographyColumnsId id) {
		this.id = id;
	}

	public GeographyColumnsId getId() {
		return this.id;
	}

	public void setId(GeographyColumnsId id) {
		this.id = id;
	}

}
