package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

/**
 * GeometryColumns generated by hbm2java
 */
public class GeometryColumns implements java.io.Serializable {

	private GeometryColumnsId id;

	public GeometryColumns() {
	}

	public GeometryColumns(GeometryColumnsId id) {
		this.id = id;
	}

	public GeometryColumnsId getId() {
		return this.id;
	}

	public void setId(GeometryColumnsId id) {
		this.id = id;
	}

}
