package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

/**
 * InvoiceAudit generated by hbm2java
 */
public class InvoiceAudit implements java.io.Serializable {

	private InvoiceAuditId id;

	public InvoiceAudit() {
	}

	public InvoiceAudit(InvoiceAuditId id) {
		this.id = id;
	}

	public InvoiceAuditId getId() {
		return this.id;
	}

	public void setId(InvoiceAuditId id) {
		this.id = id;
	}

}
