package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

/**
 * InvoiceLineItemAudit generated by hbm2java
 */
public class InvoiceLineItemAudit implements java.io.Serializable {

	private InvoiceLineItemAuditId id;

	public InvoiceLineItemAudit() {
	}

	public InvoiceLineItemAudit(InvoiceLineItemAuditId id) {
		this.id = id;
	}

	public InvoiceLineItemAuditId getId() {
		return this.id;
	}

	public void setId(InvoiceLineItemAuditId id) {
		this.id = id;
	}

}
