package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

import java.util.Date;

/**
 * InvoiceLineItemAuditId generated by hbm2java
 */
public class InvoiceLineItemAuditId implements java.io.Serializable {

	private Character action;
	private Long id;
	private Long invoiceId;
	private Long kotId;
	private Long botId;
	private Double price;
	private Date updatedAt;
	private Long updatedBy;

	public InvoiceLineItemAuditId() {
	}

	public InvoiceLineItemAuditId(Character action, Long id, Long invoiceId, Long kotId, Long botId, Double price,
			Date updatedAt, Long updatedBy) {
		this.action = action;
		this.id = id;
		this.invoiceId = invoiceId;
		this.kotId = kotId;
		this.botId = botId;
		this.price = price;
		this.updatedAt = updatedAt;
		this.updatedBy = updatedBy;
	}

	public Character getAction() {
		return this.action;
	}

	public void setAction(Character action) {
		this.action = action;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getInvoiceId() {
		return this.invoiceId;
	}

	public void setInvoiceId(Long invoiceId) {
		this.invoiceId = invoiceId;
	}

	public Long getKotId() {
		return this.kotId;
	}

	public void setKotId(Long kotId) {
		this.kotId = kotId;
	}

	public Long getBotId() {
		return this.botId;
	}

	public void setBotId(Long botId) {
		this.botId = botId;
	}

	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Long updatedBy) {
		this.updatedBy = updatedBy;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InvoiceLineItemAuditId))
			return false;
		InvoiceLineItemAuditId castOther = (InvoiceLineItemAuditId) other;

		return ((this.getAction() == castOther.getAction()) || (this.getAction() != null
				&& castOther.getAction() != null && this.getAction().equals(castOther.getAction())))
				&& ((this.getId() == castOther.getId()) || (this.getId() != null && castOther.getId() != null
						&& this.getId().equals(castOther.getId())))
				&& ((this.getInvoiceId() == castOther.getInvoiceId()) || (this.getInvoiceId() != null
						&& castOther.getInvoiceId() != null && this.getInvoiceId().equals(castOther.getInvoiceId())))
				&& ((this.getKotId() == castOther.getKotId()) || (this.getKotId() != null
						&& castOther.getKotId() != null && this.getKotId().equals(castOther.getKotId())))
				&& ((this.getBotId() == castOther.getBotId()) || (this.getBotId() != null
						&& castOther.getBotId() != null && this.getBotId().equals(castOther.getBotId())))
				&& ((this.getPrice() == castOther.getPrice()) || (this.getPrice() != null
						&& castOther.getPrice() != null && this.getPrice().equals(castOther.getPrice())))
				&& ((this.getUpdatedAt() == castOther.getUpdatedAt()) || (this.getUpdatedAt() != null
						&& castOther.getUpdatedAt() != null && this.getUpdatedAt().equals(castOther.getUpdatedAt())))
				&& ((this.getUpdatedBy() == castOther.getUpdatedBy()) || (this.getUpdatedBy() != null
						&& castOther.getUpdatedBy() != null && this.getUpdatedBy().equals(castOther.getUpdatedBy())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAction() == null ? 0 : this.getAction().hashCode());
		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getInvoiceId() == null ? 0 : this.getInvoiceId().hashCode());
		result = 37 * result + (getKotId() == null ? 0 : this.getKotId().hashCode());
		result = 37 * result + (getBotId() == null ? 0 : this.getBotId().hashCode());
		result = 37 * result + (getPrice() == null ? 0 : this.getPrice().hashCode());
		result = 37 * result + (getUpdatedAt() == null ? 0 : this.getUpdatedAt().hashCode());
		result = 37 * result + (getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode());
		return result;
	}

}
