package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * KitchenMenuItem generated by hbm2java
 */
public class KitchenMenuItem implements java.io.Serializable {

	private long id;
	private Currency currency;
	private KitchenMenu kitchenMenu;
	private String name;
	private Double price;
	private Integer calories;
	private Integer serves;
	private Integer spicyRating;
	private String description;
	private Serializable itemType;
	private Serializable itemSubtype;
	private Date updatedAt;
	private Long updatedBy;
	private Set reviews = new HashSet(0);

	public KitchenMenuItem() {
	}

	public KitchenMenuItem(long id) {
		this.id = id;
	}

	public KitchenMenuItem(long id, Currency currency, KitchenMenu kitchenMenu, String name, Double price,
			Integer calories, Integer serves, Integer spicyRating, String description, Serializable itemType,
			Serializable itemSubtype, Date updatedAt, Long updatedBy, Set reviews) {
		this.id = id;
		this.currency = currency;
		this.kitchenMenu = kitchenMenu;
		this.name = name;
		this.price = price;
		this.calories = calories;
		this.serves = serves;
		this.spicyRating = spicyRating;
		this.description = description;
		this.itemType = itemType;
		this.itemSubtype = itemSubtype;
		this.updatedAt = updatedAt;
		this.updatedBy = updatedBy;
		this.reviews = reviews;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Currency getCurrency() {
		return this.currency;
	}

	public void setCurrency(Currency currency) {
		this.currency = currency;
	}

	public KitchenMenu getKitchenMenu() {
		return this.kitchenMenu;
	}

	public void setKitchenMenu(KitchenMenu kitchenMenu) {
		this.kitchenMenu = kitchenMenu;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public Integer getCalories() {
		return this.calories;
	}

	public void setCalories(Integer calories) {
		this.calories = calories;
	}

	public Integer getServes() {
		return this.serves;
	}

	public void setServes(Integer serves) {
		this.serves = serves;
	}

	public Integer getSpicyRating() {
		return this.spicyRating;
	}

	public void setSpicyRating(Integer spicyRating) {
		this.spicyRating = spicyRating;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Serializable getItemType() {
		return this.itemType;
	}

	public void setItemType(Serializable itemType) {
		this.itemType = itemType;
	}

	public Serializable getItemSubtype() {
		return this.itemSubtype;
	}

	public void setItemSubtype(Serializable itemSubtype) {
		this.itemSubtype = itemSubtype;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Long updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Set getReviews() {
		return this.reviews;
	}

	public void setReviews(Set reviews) {
		this.reviews = reviews;
	}

}
