package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

/**
 * KitchenMenuItemAudit generated by hbm2java
 */
public class KitchenMenuItemAudit implements java.io.Serializable {

	private KitchenMenuItemAuditId id;

	public KitchenMenuItemAudit() {
	}

	public KitchenMenuItemAudit(KitchenMenuItemAuditId id) {
		this.id = id;
	}

	public KitchenMenuItemAuditId getId() {
		return this.id;
	}

	public void setId(KitchenMenuItemAuditId id) {
		this.id = id;
	}

}
