package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

/**
 * KitchenMenuAudit generated by hbm2java
 */
public class KitchenMenuAudit implements java.io.Serializable {

	private KitchenMenuAuditId id;

	public KitchenMenuAudit() {
	}

	public KitchenMenuAudit(KitchenMenuAuditId id) {
		this.id = id;
	}

	public KitchenMenuAuditId getId() {
		return this.id;
	}

	public void setId(KitchenMenuAuditId id) {
		this.id = id;
	}

}
