package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Kot generated by hbm2java
 */
public class Kot implements java.io.Serializable {

	private long id;
	private Kot kot;
	private Session session;
	private Integer qty;
	private Date updatedAt;
	private Long updatedBy;
	private Set invoiceLineItems = new HashSet(0);
	private Set kots = new HashSet(0);

	public Kot() {
	}

	public Kot(long id) {
		this.id = id;
	}

	public Kot(long id, Kot kot, Session session, Integer qty, Date updatedAt, Long updatedBy, Set invoiceLineItems,
			Set kots) {
		this.id = id;
		this.kot = kot;
		this.session = session;
		this.qty = qty;
		this.updatedAt = updatedAt;
		this.updatedBy = updatedBy;
		this.invoiceLineItems = invoiceLineItems;
		this.kots = kots;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Kot getKot() {
		return this.kot;
	}

	public void setKot(Kot kot) {
		this.kot = kot;
	}

	public Session getSession() {
		return this.session;
	}

	public void setSession(Session session) {
		this.session = session;
	}

	public Integer getQty() {
		return this.qty;
	}

	public void setQty(Integer qty) {
		this.qty = qty;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Long updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Set getInvoiceLineItems() {
		return this.invoiceLineItems;
	}

	public void setInvoiceLineItems(Set invoiceLineItems) {
		this.invoiceLineItems = invoiceLineItems;
	}

	public Set getKots() {
		return this.kots;
	}

	public void setKots(Set kots) {
		this.kots = kots;
	}

}
