package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

/**
 * KotAudit generated by hbm2java
 */
public class KotAudit implements java.io.Serializable {

	private KotAuditId id;

	public KotAudit() {
	}

	public KotAudit(KotAuditId id) {
		this.id = id;
	}

	public KotAuditId getId() {
		return this.id;
	}

	public void setId(KotAuditId id) {
		this.id = id;
	}

}
