package com.ignis.model;
// Generated 4 Aug, 2019 8:15:16 PM by Hibernate Tools 5.4.3.Final

/**
 * LayoutAudit generated by hbm2java
 */
public class LayoutAudit implements java.io.Serializable {

	private LayoutAuditId id;

	public LayoutAudit() {
	}

	public LayoutAudit(LayoutAuditId id) {
		this.id = id;
	}

	public LayoutAuditId getId() {
		return this.id;
	}

	public void setId(LayoutAuditId id) {
		this.id = id;
	}

}
