package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

/**
 * MemoriesAudit generated by hbm2java
 */
public class MemoriesAudit implements java.io.Serializable {

	private MemoriesAuditId id;

	public MemoriesAudit() {
	}

	public MemoriesAudit(MemoriesAuditId id) {
		this.id = id;
	}

	public MemoriesAuditId getId() {
		return this.id;
	}

	public void setId(MemoriesAuditId id) {
		this.id = id;
	}

}
