package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

import java.io.Serializable;
import java.util.Date;

/**
 * Memories generated by hbm2java
 */
public class Memories implements java.io.Serializable {

	private long id;
	private Customer customer;
	private Session session;
	private SessionGroup sessionGroup;
	private Date time;
	private byte[] image;
	private String url;
	private Serializable shareWithOthers;
	private Date updatedAt;
	private Long updatedBy;

	public Memories() {
	}

	public Memories(long id, Customer customer) {
		this.id = id;
		this.customer = customer;
	}

	public Memories(long id, Customer customer, Session session, SessionGroup sessionGroup, Date time, byte[] image,
			String url, Serializable shareWithOthers, Date updatedAt, Long updatedBy) {
		this.id = id;
		this.customer = customer;
		this.session = session;
		this.sessionGroup = sessionGroup;
		this.time = time;
		this.image = image;
		this.url = url;
		this.shareWithOthers = shareWithOthers;
		this.updatedAt = updatedAt;
		this.updatedBy = updatedBy;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Session getSession() {
		return this.session;
	}

	public void setSession(Session session) {
		this.session = session;
	}

	public SessionGroup getSessionGroup() {
		return this.sessionGroup;
	}

	public void setSessionGroup(SessionGroup sessionGroup) {
		this.sessionGroup = sessionGroup;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Serializable getShareWithOthers() {
		return this.shareWithOthers;
	}

	public void setShareWithOthers(Serializable shareWithOthers) {
		this.shareWithOthers = shareWithOthers;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Long updatedBy) {
		this.updatedBy = updatedBy;
	}

}
