package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

import java.io.Serializable;
import java.util.Arrays;
import java.util.Date;

/**
 * MemoriesAuditId generated by hbm2java
 */
public class MemoriesAuditId implements java.io.Serializable {

	private Character action;
	private long id;
	private Date time;
	private long customerId;
	private Long sessionId;
	private Long sessionGroupId;
	private byte[] image;
	private String url;
	private Serializable shareWithOthers;
	private Date updatedAt;
	private Long updatedBy;

	public MemoriesAuditId() {
	}

	public MemoriesAuditId(long id, long customerId) {
		this.id = id;
		this.customerId = customerId;
	}

	public MemoriesAuditId(Character action, long id, Date time, long customerId, Long sessionId, Long sessionGroupId,
			byte[] image, String url, Serializable shareWithOthers, Date updatedAt, Long updatedBy) {
		this.action = action;
		this.id = id;
		this.time = time;
		this.customerId = customerId;
		this.sessionId = sessionId;
		this.sessionGroupId = sessionGroupId;
		this.image = image;
		this.url = url;
		this.shareWithOthers = shareWithOthers;
		this.updatedAt = updatedAt;
		this.updatedBy = updatedBy;
	}

	public Character getAction() {
		return this.action;
	}

	public void setAction(Character action) {
		this.action = action;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public long getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(long customerId) {
		this.customerId = customerId;
	}

	public Long getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(Long sessionId) {
		this.sessionId = sessionId;
	}

	public Long getSessionGroupId() {
		return this.sessionGroupId;
	}

	public void setSessionGroupId(Long sessionGroupId) {
		this.sessionGroupId = sessionGroupId;
	}

	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Serializable getShareWithOthers() {
		return this.shareWithOthers;
	}

	public void setShareWithOthers(Serializable shareWithOthers) {
		this.shareWithOthers = shareWithOthers;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Long updatedBy) {
		this.updatedBy = updatedBy;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MemoriesAuditId))
			return false;
		MemoriesAuditId castOther = (MemoriesAuditId) other;

		return ((this.getAction() == castOther.getAction()) || (this.getAction() != null
				&& castOther.getAction() != null && this.getAction().equals(castOther.getAction())))
				&& (this.getId() == castOther.getId())
				&& ((this.getTime() == castOther.getTime()) || (this.getTime() != null && castOther.getTime() != null
						&& this.getTime().equals(castOther.getTime())))
				&& (this.getCustomerId() == castOther.getCustomerId())
				&& ((this.getSessionId() == castOther.getSessionId()) || (this.getSessionId() != null
						&& castOther.getSessionId() != null && this.getSessionId().equals(castOther.getSessionId())))
				&& ((this.getSessionGroupId() == castOther.getSessionGroupId())
						|| (this.getSessionGroupId() != null && castOther.getSessionGroupId() != null
								&& this.getSessionGroupId().equals(castOther.getSessionGroupId())))
				&& ((this.getImage() == castOther.getImage()) || (this.getImage() != null
						&& castOther.getImage() != null && Arrays.equals(this.getImage(), castOther.getImage())))
				&& ((this.getUrl() == castOther.getUrl()) || (this.getUrl() != null && castOther.getUrl() != null
						&& this.getUrl().equals(castOther.getUrl())))
				&& ((this.getShareWithOthers() == castOther.getShareWithOthers())
						|| (this.getShareWithOthers() != null && castOther.getShareWithOthers() != null
								&& this.getShareWithOthers().equals(castOther.getShareWithOthers())))
				&& ((this.getUpdatedAt() == castOther.getUpdatedAt()) || (this.getUpdatedAt() != null
						&& castOther.getUpdatedAt() != null && this.getUpdatedAt().equals(castOther.getUpdatedAt())))
				&& ((this.getUpdatedBy() == castOther.getUpdatedBy()) || (this.getUpdatedBy() != null
						&& castOther.getUpdatedBy() != null && this.getUpdatedBy().equals(castOther.getUpdatedBy())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAction() == null ? 0 : this.getAction().hashCode());
		result = 37 * result + (int) this.getId();
		result = 37 * result + (getTime() == null ? 0 : this.getTime().hashCode());
		result = 37 * result + (int) this.getCustomerId();
		result = 37 * result + (getSessionId() == null ? 0 : this.getSessionId().hashCode());
		result = 37 * result + (getSessionGroupId() == null ? 0 : this.getSessionGroupId().hashCode());
		int imageHashcode = 0;
		byte[] imageProperty = this.getImage();
		if (imageProperty != null) {
			imageHashcode = 1;
			for (int i = 0; i < imageProperty.length; i++) {
				imageHashcode = 37 * imageHashcode + imageProperty[i];
			}
		}

		result = 37 * result + imageHashcode;

		result = 37 * result + (getUrl() == null ? 0 : this.getUrl().hashCode());
		result = 37 * result + (getShareWithOthers() == null ? 0 : this.getShareWithOthers().hashCode());
		result = 37 * result + (getUpdatedAt() == null ? 0 : this.getUpdatedAt().hashCode());
		result = 37 * result + (getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode());
		return result;
	}

}
