package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

import java.io.Serializable;
import java.util.Date;

/**
 * Promotion generated by hbm2java
 */
public class Promotion implements java.io.Serializable {

	private long id;
	private Entity entity;
	private Staff staff;
	private String message;
	private byte[] image;
	private Date startDatetime;
	private Date endDatetime;
	private Boolean isActive;
	private Serializable type;
	private Serializable frequency;
	private Date updatedAt;
	private Long updatedBy;

	public Promotion() {
	}

	public Promotion(long id, Entity entity) {
		this.id = id;
		this.entity = entity;
	}

	public Promotion(long id, Entity entity, Staff staff, String message, byte[] image, Date startDatetime,
			Date endDatetime, Boolean isActive, Serializable type, Serializable frequency, Date updatedAt,
			Long updatedBy) {
		this.id = id;
		this.entity = entity;
		this.staff = staff;
		this.message = message;
		this.image = image;
		this.startDatetime = startDatetime;
		this.endDatetime = endDatetime;
		this.isActive = isActive;
		this.type = type;
		this.frequency = frequency;
		this.updatedAt = updatedAt;
		this.updatedBy = updatedBy;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Entity getEntity() {
		return this.entity;
	}

	public void setEntity(Entity entity) {
		this.entity = entity;
	}

	public Staff getStaff() {
		return this.staff;
	}

	public void setStaff(Staff staff) {
		this.staff = staff;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	public Date getStartDatetime() {
		return this.startDatetime;
	}

	public void setStartDatetime(Date startDatetime) {
		this.startDatetime = startDatetime;
	}

	public Date getEndDatetime() {
		return this.endDatetime;
	}

	public void setEndDatetime(Date endDatetime) {
		this.endDatetime = endDatetime;
	}

	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public Serializable getType() {
		return this.type;
	}

	public void setType(Serializable type) {
		this.type = type;
	}

	public Serializable getFrequency() {
		return this.frequency;
	}

	public void setFrequency(Serializable frequency) {
		this.frequency = frequency;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Long updatedBy) {
		this.updatedBy = updatedBy;
	}

}
