package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

/**
 * PromotionAudit generated by hbm2java
 */
public class PromotionAudit implements java.io.Serializable {

	private PromotionAuditId id;

	public PromotionAudit() {
	}

	public PromotionAudit(PromotionAuditId id) {
		this.id = id;
	}

	public PromotionAuditId getId() {
		return this.id;
	}

	public void setId(PromotionAuditId id) {
		this.id = id;
	}

}
