package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

/**
 * RasterColumns generated by hbm2java
 */
public class RasterColumns implements java.io.Serializable {

	private RasterColumnsId id;

	public RasterColumns() {
	}

	public RasterColumns(RasterColumnsId id) {
		this.id = id;
	}

	public RasterColumnsId getId() {
		return this.id;
	}

	public void setId(RasterColumnsId id) {
		this.id = id;
	}

}
