package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

/**
 * RasterOverviews generated by hbm2java
 */
public class RasterOverviews implements java.io.Serializable {

	private RasterOverviewsId id;

	public RasterOverviews() {
	}

	public RasterOverviews(RasterOverviewsId id) {
		this.id = id;
	}

	public RasterOverviewsId getId() {
		return this.id;
	}

	public void setId(RasterOverviewsId id) {
		this.id = id;
	}

}
