package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * RatingScale generated by hbm2java
 */
public class RatingScale implements java.io.Serializable {

	private int id;
	private String name;
	private Integer value;
	private String description;
	private Set entities = new HashSet(0);

	public RatingScale() {
	}

	public RatingScale(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public RatingScale(int id, String name, Integer value, String description, Set entities) {
		this.id = id;
		this.name = name;
		this.value = value;
		this.description = description;
		this.entities = entities;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getValue() {
		return this.value;
	}

	public void setValue(Integer value) {
		this.value = value;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getEntities() {
		return this.entities;
	}

	public void setEntities(Set entities) {
		this.entities = entities;
	}

}
