package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

/**
 * ReviewAudit generated by hbm2java
 */
public class ReviewAudit implements java.io.Serializable {

	private ReviewAuditId id;

	public ReviewAudit() {
	}

	public ReviewAudit(ReviewAuditId id) {
		this.id = id;
	}

	public ReviewAuditId getId() {
		return this.id;
	}

	public void setId(ReviewAuditId id) {
		this.id = id;
	}

}
