package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

import java.util.Date;

/**
 * ReviewAuditId generated by hbm2java
 */
public class ReviewAuditId implements java.io.Serializable {

	private Character action;
	private Long id;
	private Long establishmentId;
	private Long menuItemId;
	private Long customerId;
	private String comments;
	private Integer rating;
	private Date updatedAt;
	private Long updatedBy;

	public ReviewAuditId() {
	}

	public ReviewAuditId(Character action, Long id, Long establishmentId, Long menuItemId, Long customerId,
			String comments, Integer rating, Date updatedAt, Long updatedBy) {
		this.action = action;
		this.id = id;
		this.establishmentId = establishmentId;
		this.menuItemId = menuItemId;
		this.customerId = customerId;
		this.comments = comments;
		this.rating = rating;
		this.updatedAt = updatedAt;
		this.updatedBy = updatedBy;
	}

	public Character getAction() {
		return this.action;
	}

	public void setAction(Character action) {
		this.action = action;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getEstablishmentId() {
		return this.establishmentId;
	}

	public void setEstablishmentId(Long establishmentId) {
		this.establishmentId = establishmentId;
	}

	public Long getMenuItemId() {
		return this.menuItemId;
	}

	public void setMenuItemId(Long menuItemId) {
		this.menuItemId = menuItemId;
	}

	public Long getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Long customerId) {
		this.customerId = customerId;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public Integer getRating() {
		return this.rating;
	}

	public void setRating(Integer rating) {
		this.rating = rating;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Long updatedBy) {
		this.updatedBy = updatedBy;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReviewAuditId))
			return false;
		ReviewAuditId castOther = (ReviewAuditId) other;

		return ((this.getAction() == castOther.getAction()) || (this.getAction() != null
				&& castOther.getAction() != null && this.getAction().equals(castOther.getAction())))
				&& ((this.getId() == castOther.getId()) || (this.getId() != null && castOther.getId() != null
						&& this.getId().equals(castOther.getId())))
				&& ((this.getEstablishmentId() == castOther.getEstablishmentId())
						|| (this.getEstablishmentId() != null && castOther.getEstablishmentId() != null
								&& this.getEstablishmentId().equals(castOther.getEstablishmentId())))
				&& ((this.getMenuItemId() == castOther.getMenuItemId()) || (this.getMenuItemId() != null
						&& castOther.getMenuItemId() != null && this.getMenuItemId().equals(castOther.getMenuItemId())))
				&& ((this.getCustomerId() == castOther.getCustomerId()) || (this.getCustomerId() != null
						&& castOther.getCustomerId() != null && this.getCustomerId().equals(castOther.getCustomerId())))
				&& ((this.getComments() == castOther.getComments()) || (this.getComments() != null
						&& castOther.getComments() != null && this.getComments().equals(castOther.getComments())))
				&& ((this.getRating() == castOther.getRating()) || (this.getRating() != null
						&& castOther.getRating() != null && this.getRating().equals(castOther.getRating())))
				&& ((this.getUpdatedAt() == castOther.getUpdatedAt()) || (this.getUpdatedAt() != null
						&& castOther.getUpdatedAt() != null && this.getUpdatedAt().equals(castOther.getUpdatedAt())))
				&& ((this.getUpdatedBy() == castOther.getUpdatedBy()) || (this.getUpdatedBy() != null
						&& castOther.getUpdatedBy() != null && this.getUpdatedBy().equals(castOther.getUpdatedBy())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAction() == null ? 0 : this.getAction().hashCode());
		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getEstablishmentId() == null ? 0 : this.getEstablishmentId().hashCode());
		result = 37 * result + (getMenuItemId() == null ? 0 : this.getMenuItemId().hashCode());
		result = 37 * result + (getCustomerId() == null ? 0 : this.getCustomerId().hashCode());
		result = 37 * result + (getComments() == null ? 0 : this.getComments().hashCode());
		result = 37 * result + (getRating() == null ? 0 : this.getRating().hashCode());
		result = 37 * result + (getUpdatedAt() == null ? 0 : this.getUpdatedAt().hashCode());
		result = 37 * result + (getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode());
		return result;
	}

}
