package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

/**
 * SessionCustomerId generated by hbm2java
 */
public class SessionCustomerId implements java.io.Serializable {

	private long sessionId;
	private long customerId;
	private Boolean isPayer;

	public SessionCustomerId() {
	}

	public SessionCustomerId(long sessionId, long customerId) {
		this.sessionId = sessionId;
		this.customerId = customerId;
	}

	public SessionCustomerId(long sessionId, long customerId, Boolean isPayer) {
		this.sessionId = sessionId;
		this.customerId = customerId;
		this.isPayer = isPayer;
	}

	public long getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(long sessionId) {
		this.sessionId = sessionId;
	}

	public long getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(long customerId) {
		this.customerId = customerId;
	}

	public Boolean getIsPayer() {
		return this.isPayer;
	}

	public void setIsPayer(Boolean isPayer) {
		this.isPayer = isPayer;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SessionCustomerId))
			return false;
		SessionCustomerId castOther = (SessionCustomerId) other;

		return (this.getSessionId() == castOther.getSessionId()) && (this.getCustomerId() == castOther.getCustomerId())
				&& ((this.getIsPayer() == castOther.getIsPayer()) || (this.getIsPayer() != null
						&& castOther.getIsPayer() != null && this.getIsPayer().equals(castOther.getIsPayer())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getSessionId();
		result = 37 * result + (int) this.getCustomerId();
		result = 37 * result + (getIsPayer() == null ? 0 : this.getIsPayer().hashCode());
		return result;
	}

}
