package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

/**
 * SessionCustomer generated by hbm2java
 */
public class SessionCustomer implements java.io.Serializable {

	private SessionCustomerId id;
	private Customer customer;
	private Session session;

	public SessionCustomer() {
	}

	public SessionCustomer(SessionCustomerId id, Customer customer, Session session) {
		this.id = id;
		this.customer = customer;
		this.session = session;
	}

	public SessionCustomerId getId() {
		return this.id;
	}

	public void setId(SessionCustomerId id) {
		this.id = id;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Session getSession() {
		return this.session;
	}

	public void setSession(Session session) {
		this.session = session;
	}

}
