package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

import java.io.Serializable;
import java.util.Date;

/**
 * SessionAuditId generated by hbm2java
 */
public class SessionAuditId implements java.io.Serializable {

	private Character action;
	private long id;
	private Long bookingId;
	private Date startTime;
	private Date endTime;
	private long diningTableId;
	private Float spendLimit;
	private Serializable status;
	private Serializable tags;
	private Date updatedAt;
	private Long updatedBy;

	public SessionAuditId() {
	}

	public SessionAuditId(long id, long diningTableId) {
		this.id = id;
		this.diningTableId = diningTableId;
	}

	public SessionAuditId(Character action, long id, Long bookingId, Date startTime, Date endTime, long diningTableId,
			Float spendLimit, Serializable status, Serializable tags, Date updatedAt, Long updatedBy) {
		this.action = action;
		this.id = id;
		this.bookingId = bookingId;
		this.startTime = startTime;
		this.endTime = endTime;
		this.diningTableId = diningTableId;
		this.spendLimit = spendLimit;
		this.status = status;
		this.tags = tags;
		this.updatedAt = updatedAt;
		this.updatedBy = updatedBy;
	}

	public Character getAction() {
		return this.action;
	}

	public void setAction(Character action) {
		this.action = action;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Long getBookingId() {
		return this.bookingId;
	}

	public void setBookingId(Long bookingId) {
		this.bookingId = bookingId;
	}

	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public long getDiningTableId() {
		return this.diningTableId;
	}

	public void setDiningTableId(long diningTableId) {
		this.diningTableId = diningTableId;
	}

	public Float getSpendLimit() {
		return this.spendLimit;
	}

	public void setSpendLimit(Float spendLimit) {
		this.spendLimit = spendLimit;
	}

	public Serializable getStatus() {
		return this.status;
	}

	public void setStatus(Serializable status) {
		this.status = status;
	}

	public Serializable getTags() {
		return this.tags;
	}

	public void setTags(Serializable tags) {
		this.tags = tags;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Long updatedBy) {
		this.updatedBy = updatedBy;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SessionAuditId))
			return false;
		SessionAuditId castOther = (SessionAuditId) other;

		return ((this.getAction() == castOther.getAction()) || (this.getAction() != null
				&& castOther.getAction() != null && this.getAction().equals(castOther.getAction())))
				&& (this.getId() == castOther.getId())
				&& ((this.getBookingId() == castOther.getBookingId()) || (this.getBookingId() != null
						&& castOther.getBookingId() != null && this.getBookingId().equals(castOther.getBookingId())))
				&& ((this.getStartTime() == castOther.getStartTime()) || (this.getStartTime() != null
						&& castOther.getStartTime() != null && this.getStartTime().equals(castOther.getStartTime())))
				&& ((this.getEndTime() == castOther.getEndTime()) || (this.getEndTime() != null
						&& castOther.getEndTime() != null && this.getEndTime().equals(castOther.getEndTime())))
				&& (this.getDiningTableId() == castOther.getDiningTableId())
				&& ((this.getSpendLimit() == castOther.getSpendLimit()) || (this.getSpendLimit() != null
						&& castOther.getSpendLimit() != null && this.getSpendLimit().equals(castOther.getSpendLimit())))
				&& ((this.getStatus() == castOther.getStatus()) || (this.getStatus() != null
						&& castOther.getStatus() != null && this.getStatus().equals(castOther.getStatus())))
				&& ((this.getTags() == castOther.getTags()) || (this.getTags() != null && castOther.getTags() != null
						&& this.getTags().equals(castOther.getTags())))
				&& ((this.getUpdatedAt() == castOther.getUpdatedAt()) || (this.getUpdatedAt() != null
						&& castOther.getUpdatedAt() != null && this.getUpdatedAt().equals(castOther.getUpdatedAt())))
				&& ((this.getUpdatedBy() == castOther.getUpdatedBy()) || (this.getUpdatedBy() != null
						&& castOther.getUpdatedBy() != null && this.getUpdatedBy().equals(castOther.getUpdatedBy())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAction() == null ? 0 : this.getAction().hashCode());
		result = 37 * result + (int) this.getId();
		result = 37 * result + (getBookingId() == null ? 0 : this.getBookingId().hashCode());
		result = 37 * result + (getStartTime() == null ? 0 : this.getStartTime().hashCode());
		result = 37 * result + (getEndTime() == null ? 0 : this.getEndTime().hashCode());
		result = 37 * result + (int) this.getDiningTableId();
		result = 37 * result + (getSpendLimit() == null ? 0 : this.getSpendLimit().hashCode());
		result = 37 * result + (getStatus() == null ? 0 : this.getStatus().hashCode());
		result = 37 * result + (getTags() == null ? 0 : this.getTags().hashCode());
		result = 37 * result + (getUpdatedAt() == null ? 0 : this.getUpdatedAt().hashCode());
		result = 37 * result + (getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode());
		return result;
	}

}
