package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

/**
 * SessionAudit generated by hbm2java
 */
public class SessionAudit implements java.io.Serializable {

	private SessionAuditId id;

	public SessionAudit() {
	}

	public SessionAudit(SessionAuditId id) {
		this.id = id;
	}

	public SessionAuditId getId() {
		return this.id;
	}

	public void setId(SessionAuditId id) {
		this.id = id;
	}

}
