package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SessionGroup generated by hbm2java
 */
public class SessionGroup implements java.io.Serializable {

	private long id;
	private Serializable sessionId;
	private Date updatedAt;
	private Long updatedBy;
	private Set memorieses = new HashSet(0);

	public SessionGroup() {
	}

	public SessionGroup(long id) {
		this.id = id;
	}

	public SessionGroup(long id, Serializable sessionId, Date updatedAt, Long updatedBy, Set memorieses) {
		this.id = id;
		this.sessionId = sessionId;
		this.updatedAt = updatedAt;
		this.updatedBy = updatedBy;
		this.memorieses = memorieses;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Serializable getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(Serializable sessionId) {
		this.sessionId = sessionId;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Long updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Set getMemorieses() {
		return this.memorieses;
	}

	public void setMemorieses(Set memorieses) {
		this.memorieses = memorieses;
	}

}
