package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Session generated by hbm2java
 */
public class Session implements java.io.Serializable {

	private long id;
	private Booking booking;
	private DiningTable diningTable;
	private Staff staff;
	private Date startTime;
	private Date endTime;
	private Float spendLimit;
	private Serializable status;
	private Serializable tags;
	private Date updatedAt;
	private Long updatedBy;
	private Set kots = new HashSet(0);
	private Set bots = new HashSet(0);
	private Set invoices = new HashSet(0);
	private Set memorieses = new HashSet(0);
	private Set sessionCustomers = new HashSet(0);

	public Session() {
	}

	public Session(long id, DiningTable diningTable) {
		this.id = id;
		this.diningTable = diningTable;
	}

	public Session(long id, Booking booking, DiningTable diningTable, Staff staff, Date startTime, Date endTime,
			Float spendLimit, Serializable status, Serializable tags, Date updatedAt, Long updatedBy, Set kots,
			Set bots, Set invoices, Set memorieses, Set sessionCustomers) {
		this.id = id;
		this.booking = booking;
		this.diningTable = diningTable;
		this.staff = staff;
		this.startTime = startTime;
		this.endTime = endTime;
		this.spendLimit = spendLimit;
		this.status = status;
		this.tags = tags;
		this.updatedAt = updatedAt;
		this.updatedBy = updatedBy;
		this.kots = kots;
		this.bots = bots;
		this.invoices = invoices;
		this.memorieses = memorieses;
		this.sessionCustomers = sessionCustomers;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Booking getBooking() {
		return this.booking;
	}

	public void setBooking(Booking booking) {
		this.booking = booking;
	}

	public DiningTable getDiningTable() {
		return this.diningTable;
	}

	public void setDiningTable(DiningTable diningTable) {
		this.diningTable = diningTable;
	}

	public Staff getStaff() {
		return this.staff;
	}

	public void setStaff(Staff staff) {
		this.staff = staff;
	}

	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public Float getSpendLimit() {
		return this.spendLimit;
	}

	public void setSpendLimit(Float spendLimit) {
		this.spendLimit = spendLimit;
	}

	public Serializable getStatus() {
		return this.status;
	}

	public void setStatus(Serializable status) {
		this.status = status;
	}

	public Serializable getTags() {
		return this.tags;
	}

	public void setTags(Serializable tags) {
		this.tags = tags;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Long updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Set getKots() {
		return this.kots;
	}

	public void setKots(Set kots) {
		this.kots = kots;
	}

	public Set getBots() {
		return this.bots;
	}

	public void setBots(Set bots) {
		this.bots = bots;
	}

	public Set getInvoices() {
		return this.invoices;
	}

	public void setInvoices(Set invoices) {
		this.invoices = invoices;
	}

	public Set getMemorieses() {
		return this.memorieses;
	}

	public void setMemorieses(Set memorieses) {
		this.memorieses = memorieses;
	}

	public Set getSessionCustomers() {
		return this.sessionCustomers;
	}

	public void setSessionCustomers(Set sessionCustomers) {
		this.sessionCustomers = sessionCustomers;
	}

}
