package com.ignis.model;
// Generated 4 Aug, 2019 8:15:16 PM by Hibernate Tools 5.4.3.Final

/**
 * StaffAudit generated by hbm2java
 */
public class StaffAudit implements java.io.Serializable {

	private StaffAuditId id;

	public StaffAudit() {
	}

	public StaffAudit(StaffAuditId id) {
		this.id = id;
	}

	public StaffAuditId getId() {
		return this.id;
	}

	public void setId(StaffAuditId id) {
		this.id = id;
	}

}
