package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

/**
 * SysconfigAudit generated by hbm2java
 */
public class SysconfigAudit implements java.io.Serializable {

	private SysconfigAuditId id;

	public SysconfigAudit() {
	}

	public SysconfigAudit(SysconfigAuditId id) {
		this.id = id;
	}

	public SysconfigAuditId getId() {
		return this.id;
	}

	public void setId(SysconfigAuditId id) {
		this.id = id;
	}

}
