package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

/**
 * SysconfigArrCustomAudit generated by hbm2java
 */
public class SysconfigArrCustomAudit implements java.io.Serializable {

	private SysconfigArrCustomAuditId id;

	public SysconfigArrCustomAudit() {
	}

	public SysconfigArrCustomAudit(SysconfigArrCustomAuditId id) {
		this.id = id;
	}

	public SysconfigArrCustomAuditId getId() {
		return this.id;
	}

	public void setId(SysconfigArrCustomAuditId id) {
		this.id = id;
	}

}
