package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

/**
 * SysconfigArrAudit generated by hbm2java
 */
public class SysconfigArrAudit implements java.io.Serializable {

	private SysconfigArrAuditId id;

	public SysconfigArrAudit() {
	}

	public SysconfigArrAudit(SysconfigArrAuditId id) {
		this.id = id;
	}

	public SysconfigArrAuditId getId() {
		return this.id;
	}

	public void setId(SysconfigArrAuditId id) {
		this.id = id;
	}

}
