package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Sysconfig generated by hbm2java
 */
public class Sysconfig implements java.io.Serializable {

	private int id;
	private String name;
	private Boolean boolValue;
	private Integer intValue;
	private String charValue;
	private Float realValue;
	private Date updatedAt;
	private Long updatedBy;
	private Set sysconfigCustoms = new HashSet(0);

	public Sysconfig() {
	}

	public Sysconfig(int id, String name, Date updatedAt) {
		this.id = id;
		this.name = name;
		this.updatedAt = updatedAt;
	}

	public Sysconfig(int id, String name, Boolean boolValue, Integer intValue, String charValue, Float realValue,
			Date updatedAt, Long updatedBy, Set sysconfigCustoms) {
		this.id = id;
		this.name = name;
		this.boolValue = boolValue;
		this.intValue = intValue;
		this.charValue = charValue;
		this.realValue = realValue;
		this.updatedAt = updatedAt;
		this.updatedBy = updatedBy;
		this.sysconfigCustoms = sysconfigCustoms;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Boolean getBoolValue() {
		return this.boolValue;
	}

	public void setBoolValue(Boolean boolValue) {
		this.boolValue = boolValue;
	}

	public Integer getIntValue() {
		return this.intValue;
	}

	public void setIntValue(Integer intValue) {
		this.intValue = intValue;
	}

	public String getCharValue() {
		return this.charValue;
	}

	public void setCharValue(String charValue) {
		this.charValue = charValue;
	}

	public Float getRealValue() {
		return this.realValue;
	}

	public void setRealValue(Float realValue) {
		this.realValue = realValue;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Long updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Set getSysconfigCustoms() {
		return this.sysconfigCustoms;
	}

	public void setSysconfigCustoms(Set sysconfigCustoms) {
		this.sysconfigCustoms = sysconfigCustoms;
	}

}
