package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

/**
 * SysconfigCustomAudit generated by hbm2java
 */
public class SysconfigCustomAudit implements java.io.Serializable {

	private SysconfigCustomAuditId id;

	public SysconfigCustomAudit() {
	}

	public SysconfigCustomAudit(SysconfigCustomAuditId id) {
		this.id = id;
	}

	public SysconfigCustomAuditId getId() {
		return this.id;
	}

	public void setId(SysconfigCustomAuditId id) {
		this.id = id;
	}

}
