package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

import java.util.Date;

/**
 * SysconfigAuditId generated by hbm2java
 */
public class SysconfigAuditId implements java.io.Serializable {

	private Character action;
	private long id;
	private String name;
	private Boolean boolValue;
	private Integer intValue;
	private String charValue;
	private Float realValue;
	private Date updatedAt;
	private Long updatedBy;

	public SysconfigAuditId() {
	}

	public SysconfigAuditId(long id, String name, Date updatedAt) {
		this.id = id;
		this.name = name;
		this.updatedAt = updatedAt;
	}

	public SysconfigAuditId(Character action, long id, String name, Boolean boolValue, Integer intValue,
			String charValue, Float realValue, Date updatedAt, Long updatedBy) {
		this.action = action;
		this.id = id;
		this.name = name;
		this.boolValue = boolValue;
		this.intValue = intValue;
		this.charValue = charValue;
		this.realValue = realValue;
		this.updatedAt = updatedAt;
		this.updatedBy = updatedBy;
	}

	public Character getAction() {
		return this.action;
	}

	public void setAction(Character action) {
		this.action = action;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Boolean getBoolValue() {
		return this.boolValue;
	}

	public void setBoolValue(Boolean boolValue) {
		this.boolValue = boolValue;
	}

	public Integer getIntValue() {
		return this.intValue;
	}

	public void setIntValue(Integer intValue) {
		this.intValue = intValue;
	}

	public String getCharValue() {
		return this.charValue;
	}

	public void setCharValue(String charValue) {
		this.charValue = charValue;
	}

	public Float getRealValue() {
		return this.realValue;
	}

	public void setRealValue(Float realValue) {
		this.realValue = realValue;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Long updatedBy) {
		this.updatedBy = updatedBy;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SysconfigAuditId))
			return false;
		SysconfigAuditId castOther = (SysconfigAuditId) other;

		return ((this.getAction() == castOther.getAction()) || (this.getAction() != null
				&& castOther.getAction() != null && this.getAction().equals(castOther.getAction())))
				&& (this.getId() == castOther.getId())
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())))
				&& ((this.getBoolValue() == castOther.getBoolValue()) || (this.getBoolValue() != null
						&& castOther.getBoolValue() != null && this.getBoolValue().equals(castOther.getBoolValue())))
				&& ((this.getIntValue() == castOther.getIntValue()) || (this.getIntValue() != null
						&& castOther.getIntValue() != null && this.getIntValue().equals(castOther.getIntValue())))
				&& ((this.getCharValue() == castOther.getCharValue()) || (this.getCharValue() != null
						&& castOther.getCharValue() != null && this.getCharValue().equals(castOther.getCharValue())))
				&& ((this.getRealValue() == castOther.getRealValue()) || (this.getRealValue() != null
						&& castOther.getRealValue() != null && this.getRealValue().equals(castOther.getRealValue())))
				&& ((this.getUpdatedAt() == castOther.getUpdatedAt()) || (this.getUpdatedAt() != null
						&& castOther.getUpdatedAt() != null && this.getUpdatedAt().equals(castOther.getUpdatedAt())))
				&& ((this.getUpdatedBy() == castOther.getUpdatedBy()) || (this.getUpdatedBy() != null
						&& castOther.getUpdatedBy() != null && this.getUpdatedBy().equals(castOther.getUpdatedBy())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAction() == null ? 0 : this.getAction().hashCode());
		result = 37 * result + (int) this.getId();
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getBoolValue() == null ? 0 : this.getBoolValue().hashCode());
		result = 37 * result + (getIntValue() == null ? 0 : this.getIntValue().hashCode());
		result = 37 * result + (getCharValue() == null ? 0 : this.getCharValue().hashCode());
		result = 37 * result + (getRealValue() == null ? 0 : this.getRealValue().hashCode());
		result = 37 * result + (getUpdatedAt() == null ? 0 : this.getUpdatedAt().hashCode());
		result = 37 * result + (getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode());
		return result;
	}

}
