package com.ignis.model;
// Generated 4 Aug, 2019 8:15:16 PM by Hibernate Tools 5.4.3.Final

/**
 * SysuserAudit generated by hbm2java
 */
public class SysuserAudit implements java.io.Serializable {

	private SysuserAuditId id;

	public SysuserAudit() {
	}

	public SysuserAudit(SysuserAuditId id) {
		this.id = id;
	}

	public SysuserAuditId getId() {
		return this.id;
	}

	public void setId(SysuserAuditId id) {
		this.id = id;
	}

}
