package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tax generated by hbm2java
 */
public class Tax implements java.io.Serializable {

	private long id;
	private Country country;
	private String stateId;
	private String name;
	private Date startDate;
	private Date endDate;
	private Boolean isActive;
	private Date updatedAt;
	private Long updatedBy;
	private Set taxComponents = new HashSet(0);
	private Set taxEntities = new HashSet(0);

	public Tax() {
	}

	public Tax(long id) {
		this.id = id;
	}

	public Tax(long id, Country country, String stateId, String name, Date startDate, Date endDate, Boolean isActive,
			Date updatedAt, Long updatedBy, Set taxComponents, Set taxEntities) {
		this.id = id;
		this.country = country;
		this.stateId = stateId;
		this.name = name;
		this.startDate = startDate;
		this.endDate = endDate;
		this.isActive = isActive;
		this.updatedAt = updatedAt;
		this.updatedBy = updatedBy;
		this.taxComponents = taxComponents;
		this.taxEntities = taxEntities;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	public String getStateId() {
		return this.stateId;
	}

	public void setStateId(String stateId) {
		this.stateId = stateId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Long updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Set getTaxComponents() {
		return this.taxComponents;
	}

	public void setTaxComponents(Set taxComponents) {
		this.taxComponents = taxComponents;
	}

	public Set getTaxEntities() {
		return this.taxEntities;
	}

	public void setTaxEntities(Set taxEntities) {
		this.taxEntities = taxEntities;
	}

}
