package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

/**
 * TaxAudit generated by hbm2java
 */
public class TaxAudit implements java.io.Serializable {

	private TaxAuditId id;

	public TaxAudit() {
	}

	public TaxAudit(TaxAuditId id) {
		this.id = id;
	}

	public TaxAuditId getId() {
		return this.id;
	}

	public void setId(TaxAuditId id) {
		this.id = id;
	}

}
