package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

/**
 * TaxComponentAudit generated by hbm2java
 */
public class TaxComponentAudit implements java.io.Serializable {

	private TaxComponentAuditId id;

	public TaxComponentAudit() {
	}

	public TaxComponentAudit(TaxComponentAuditId id) {
		this.id = id;
	}

	public TaxComponentAuditId getId() {
		return this.id;
	}

	public void setId(TaxComponentAuditId id) {
		this.id = id;
	}

}
