package com.ignis.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

/**
 * TaxEntityAudit generated by hbm2java
 */
public class TaxEntityAudit implements java.io.Serializable {

	private TaxEntityAuditId id;

	public TaxEntityAudit() {
	}

	public TaxEntityAudit(TaxEntityAuditId id) {
		this.id = id;
	}

	public TaxEntityAuditId getId() {
		return this.id;
	}

	public void setId(TaxEntityAuditId id) {
		this.id = id;
	}

}
